"""create cast table

Revision ID: 580579d6dbcf
Revises: b7f505237ae7
Create Date: 2023-04-20 12:43:10.359193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580579d6dbcf'
down_revision = 'b7f505237ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
