"""create cast table

Revision ID: b7f505237ae7
Revises: b7bf8e644cc0
Create Date: 2023-04-20 12:38:00.139317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f505237ae7'
down_revision = 'b7bf8e644cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
